### ISSUE TITLE
cant console log a type

### ISSUE THREAD

**Issue by alexkolson** [alexbepple/kiss-and-type#1]
Get the following error:

`TypeError: Cannot convert a Symbol value to a string`

**Comment by alexbepple** [comment]
A systematic investigation reveals that behavior differs, depending on
* Node version
* `import` (with [esm](https://github.com/standard-things/esm)) vs `require`
* REPL print vs `console.log`
* the type object itself vs its `props` prop (e.g. `fooT` vs `fooT.props`)

<details>
<pre>
Node 8.16 // kat = require('./pkg/dist-node')
    > fooT = kat.createType('foo')
        accessing prop Symbol(util.inspect.custom)
        accessing prop inspect
        accessing prop Symbol(Symbol.iterator)
    > fooT.props
        accessing prop Symbol(util.inspect.custom)
        accessing prop inspect
        accessing prop Symbol(Symbol.iterator)
    > console.log(fooT)
        accessing prop Symbol(util.inspect.custom)
        accessing prop inspect
        accessing prop Symbol(Symbol.iterator)
    > console.log(fooT.props)
        accessing prop Symbol(util.inspect.custom)
        accessing prop inspect
        accessing prop Symbol(Symbol.iterator)

Node 8.16 // did not work with -r esm

Node 10.17 // kat = require('./pkg/dist-node')
    > fooT = kat.createType('foo')
        {no output regarding property access}
    > fooT.props
        {no output regarding property access}
    > console.log(fooT)
        accessing prop Symbol(nodejs.util.inspect.custom)
        accessing prop inspect
        accessing prop Symbol(Symbol.toStringTag)
        accessing prop Symbol(Symbol.iterator)
    > console.log(fooT.props)
        accessing prop Symbol(nodejs.util.inspect.custom)
        accessing prop inspect
        accessing prop Symbol(Symbol.toStringTag)
        accessing prop Symbol(Symbol.iterator)

Node 10.17 // -r esm // import {createType} from './src/create-type'
    > fooT = createType('foo')
        accessing prop Symbol(Symbol.toStringTag)
        accessing prop Symbol(nodejs.util.inspect.custom)
        accessing prop constructor
    > fooT.props
        accessing prop Symbol(Symbol.toStringTag)
        accessing prop Symbol(nodejs.util.inspect.custom)
        accessing prop constructor
    > console.log(fooT)
        accessing prop Symbol(nodejs.util.inspect.custom)
        accessing prop inspect
        accessing prop Symbol(Symbol.toStringTag)
        accessing prop Symbol(Symbol.iterator)
    > console.log(fooT.props)
        accessing prop Symbol(nodejs.util.inspect.custom)
        accessing prop inspect
        accessing prop Symbol(Symbol.toStringTag)
        accessing prop Symbol(Symbol.iterator)

Node 12.13 // kat = require('./pkg/dist-node')
    > fooT = kat.createType('foo')
        {no output regarding property access}
    > fooT.props
        {no output regarding property access}
    > console.log(fooT)
        {no output regarding property access}
    > console.log(fooT.props)
        {no output regarding property access}
    
Node 12.13 // -r esm // import {createType} from './src/create-type'
    > fooT = createType('foo')
        accessing prop Symbol(Symbol.toStringTag)
        accessing prop Symbol(nodejs.util.inspect.custom)
        accessing prop constructor
    > fooT.props
        accessing prop Symbol(Symbol.toStringTag)
        accessing prop Symbol(nodejs.util.inspect.custom)
        accessing prop constructor
    > console.log(fooT)
        {no output regarding property access}
    > console.log(fooT.props)
        accessing prop Symbol(Symbol.toStringTag)
</pre>
</details>

Taking inspiration from [here](https://stackoverflow.com/questions/46927754/proxy-get-handler-called-on-evaluation-of-proxy/46928371#46928371), this would be most precise:

```js
  if (
    prop === Symbol.toStringTag ||
    prop === util.inspect.custom ||
    prop === 'inspect' ||
    prop === Symbol.iterator
  ) {
    return
  }
```

However, `util` is not available in the browser. Therefore – and given the oddity of this problem – I actually like the solution suggested by PR #3.
