### ISSUE TITLE
need ability to get all property values

### ISSUE THREAD

**Issue by alexkolson** [alexbepple/kiss-and-type#2]
```javascript
import * as r from 'ramda';
import * as kat from 'kiss-and-type';

const foo = kat.createType(['bar'])
r.pipe(
    r.prop('props'),
    r.values
)(foo)
```
causes

```bash
TypeError: Unknown property '@@functional/placeholder'
```

**Comment by alexbepple** [comment]
Aside from the fix, @alexkolson, what do you think about adding sth like `allProps()` to types? Not only would this omit the need to do low-level operations. We could also de-dupe the list.

**Comment by alexkolson** [comment]
@alexbepple 👍

**Comment by alexbepple** [comment]
I was thinking of `allProps` as a simple way to get all the unique prop names.
`const fooT = createType([{bar: {alias: 'baz'}}])
__.assertThat(fooT.allProps(), __.is(['bar']))`

And the implementation would probably be something like `r.pipe(() => props, r.values, r.map(x => x()), r.uniq)`.

Does this make sense? Is the name badly chosen? Is `allPropNames` better? 
Should this be a method on the type? Or rather a type utility?
